spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iron_bank
    username: ironhacker
    password: 1r0nh4ck3r
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  profiles:
    active: demo

iron_bank:
  app:
    jwtSecretKey: "67566B59703373367638792F423F4528482B4D6251655468576D5A7134743777"
    jwtExpirationMs: 86400000000
